"""followers

Revision ID: 910be85f97f7
Revises: 2cbbedd29cdf
Create Date: 2023-05-29 16:51:48.813720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910be85f97f7'
down_revision = '2cbbedd29cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
